### ISSUE TITLE
OSMD renders sus chords as omit3

### ISSUE THREAD

**Issue by infojunkie** [infojunkie/ireal-musicxml#11]
As per [my blog post](https://blog.karimratib.me/2020/11/30/ireal-musicxml.html), notice the difference between MuseScore and OSMD renderings starting measure 17. To be investigated.

**Comment by infojunkie** [comment]
Who is correct? Discussion at https://github.com/w3c/musicxml/issues/352

**Comment by ericfont** [comment]
MuseScore is correct.  Those should be "sus" chords, not "omit 3".

**Comment by infojunkie** [comment]
Filed on OSMD at https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/930

**Comment by infojunkie** [comment]
Fixed by https://github.com/infojunkie/ireal-musicxml/commit/25f22c3aa13c6ccdc1feb292b08658aa1dca90bc
