### ISSUE TITLE
Chords symbols get squashed together if display window too narrow

### ISSUE THREAD

**Issue by ericfont** [infojunkie/ireal-musicxml#12]
I guess this issue is more for the rendering engine (OpenSheetMusicDisplay), but just noting that if I made the window width too narrow, the chord symbols might overlap:

![image](https://user-images.githubusercontent.com/6502474/100919989-88405680-34a8-11eb-9daa-40b9d96aa7ba.png)

I guess OpenSheetMusicDisplay doesn't take the chord symbols width into account for spacing.

**Comment by infojunkie** [comment]
Thanks. Yes, it's an OSMD issue that I plan to flag to them - will link to the issue here. I need to add a "Download MusicXML" to the demo above to be able to attach problematic files easily.

**Comment by infojunkie** [comment]
> I need to add a "Download MusicXML" to the demo above to be able to attach problematic files easily.

Done! Working for you?

**Comment by ericfont** [comment]
ah yes, thanks!

**Comment by infojunkie** [comment]
Ooops - closed too son.

**Comment by infojunkie** [comment]
This is where the work is happening: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/597

**Comment by infojunkie** [comment]
Fixed by https://github.com/infojunkie/ireal-musicxml/commit/25f22c3aa13c6ccdc1feb292b08658aa1dca90bc
