### ISSUE TITLE
502 Blues corruption reported in MuseScore

### ISSUE THREAD

**Issue by ericfont** [infojunkie/ireal-musicxml#13]
Measure 1, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 2, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 3, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 4, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 5, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 6, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 7, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 8, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 9, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 10, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 11, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 13, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 14, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 15, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 17, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 18, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 19, staff 1 incomplete. Expected: 3/4; Found: 1/1
Measure 20, staff 1 incomplete. Expected: 3/4; Found: 1/1

MuseScore reads all the dummy slash notes as whole notes.  Which are of course too big for 3/4 measure size, hence the corruption.

**Comment by ericfont** [comment]
And while MuseScore imports as whole notes, OSMD imports them as "dotted whole" notes, which are 6 beats long...too big for 3/4 measure:

![image](https://user-images.githubusercontent.com/6502474/100930306-e70ccc80-34b6-11eb-9297-99d198c4d0ae.png)

**Comment by infojunkie** [comment]
Thanks. Looks like I messed up by converting any full-measure note duration to a "whole" note, which only applies to full rests... I'll need to fix this.

**Comment by ericfont** [comment]
Same issue happens with "A Child is Born", which is also in 3/4: [A Child Is Born.zip](https://github.com/infojunkie/ireal-musicxml/files/5632800/A.Child.Is.Born.zip)

Sounds like this will happen for any song with time signature less than 4/4.

**Comment by infojunkie** [comment]
Yeah, I sort of expect that... Also 5/4 ?

**Comment by ericfont** [comment]
Take 5 doesn't report corruption:

![image](https://user-images.githubusercontent.com/6502474/100946575-ab333080-34d1-11eb-9cd3-41693fe49e9e.png)

It is worth noting that the 4th measure of section B is imported as a whole note followed by an invisible quarter rest, which works.

**Comment by ericfont** [comment]
However the OSMC imports that questionable measure as a double-dotted whole note...which is problematic:

![image](https://user-images.githubusercontent.com/6502474/100946713-ec2b4500-34d1-11eb-937e-26f31bfd81ef.png)

**Comment by ericfont** [comment]
I don't know the "best" that those type of whole-measure chord notes should be imported.

**Comment by ericfont** [comment]
I see the MusicXML file has that note as a "whole" type of duration 3840.

```
    <measure number="12">
      <harmony>
        <root>
          <root-step>G</root-step>
          <root-alter>-1</root-alter>
        </root>
        <kind text="GbM7">major-seventh</kind>
      </harmony>
      <barline location="left">
        <bar-style>none</bar-style>
      </barline>
      <note>
        <pitch>
          <step>B</step>
          <alter>-1</alter>
          <octave>4</octave>
        </pitch>
        <duration>3840</duration>
        <voice>1</voice>
        <type>whole</type>
        <notehead>slash</notehead>
      </note>
      <barline location="right">
        <bar-style>regular</bar-style>
      </barline>
    </measure>
```

**Comment by ericfont** [comment]
Attaching the MusicXML file for reference. [Take Five.zip](https://github.com/infojunkie/ireal-musicxml/files/5632838/Take.Five.zip)

**Comment by infojunkie** [comment]
Fixed on the demo - please confirm!

**Comment by ericfont** [comment]
Wow, that was fast.  That seems to have fixed it for these 3/4 songs and Take Five.  Thanks!
