### ISSUE TITLE
Post-processing for MuseScore to make sheets look nice

### ISSUE THREAD

**Issue by ericfont** [infojunkie/ireal-musicxml#16]
When the raw MusicXML is imported into MuseScore, it initially looks like:

![image](https://user-images.githubusercontent.com/6502474/101078360-0e759f00-3574-11eb-84a9-2d86844fb19c.png)

There is a bit of treatment I do for chordsymbol-only charts:

First I make the chord symbols display with MuseScore's jazz format by:
-right-clicking one chord and click style
-change "Appearance" from "Standard" to "Jazz"
![image](https://user-images.githubusercontent.com/6502474/101079256-3c0f1800-3575-11eb-9999-475ef84123c4.png)

Then I make every chord's size larger by clicking the "Text Styles" in left-most column, selecting "Chord Symbol" in subcolumn, and bumping up "Size" from default of 12pt to 18pt:
![image](https://user-images.githubusercontent.com/6502474/101079499-90b29300-3575-11eb-851e-5dadd6546a33.png)

I disable measure numbers going to "Measure Numbers" in first column and unchecking the box:
![image](https://user-images.githubusercontent.com/6502474/101079852-074f9080-3576-11eb-8d44-f9e9078e0da1.png)

I get rid of unnecessary auto-generated key & clef on each system after the first with:
![image](https://user-images.githubusercontent.com/6502474/101080179-72996280-3576-11eb-947b-808c4f0bc064.png)

The resulting sheet now look like:
![image](https://user-images.githubusercontent.com/6502474/101080294-9d83b680-3576-11eb-9b50-6405987fd3fc.png)

I've saved these style settings as:
[simple-chord-sheet.zip](https://github.com/infojunkie/ireal-musicxml/files/5638591/simple-chord-sheet.zip)

Which can be imported by extracting that file into your MuseScore directory under subdirectory "Styles", and then loaded for every score by going to "Format"->"Load Style" and opening that style.

The remaining steps I can't do with styles alone, unfortunately.  So I have to manually do the following:

First it is unnecessary to display staff lines, because there are no changing notes, and neither is the initial clef necessary.  These can be disabled by right-clicking a staff, and by unchecking "Show clef" and checking "Staff lines invisible":

![image](https://user-images.githubusercontent.com/6502474/101078703-85ab3300-3574-11eb-866f-f32057f2d6f9.png)

Now the staff lines will be greyed out in MuseScore's view:

![image](https://user-images.githubusercontent.com/6502474/101081043-8beede80-3577-11eb-9f72-02c41998d569.png)

(When exported to pdf/image or online, the staffs will be invisible.)

And one more step is to disable playback of the slash chord dummy notes.  Their playback is not desired, because the pitch defaults to the middle staff line (pitch B in treble clef), and that pitch likely will clash with MuseScore's automatically generated chord voicing sound for each chord symbol.  Normally these slash chord dummy pitches are disabled by default when generating slash chords via Tools->"Toggle Rhythmic Slash Notation", however since MuseScore doesn't know to disable their sound upon input from MusicXML, I have to manually disable their sound by right-clicking one dummy slash chord note, selecting all similar elements, and unchecking the "Play" checkboxy in the inspector (accessible via F8).

**Comment by infojunkie** [comment]
Beautiful write-up thanks!

**Comment by ericfont** [comment]
The ideal solution I imagine would be that MusicXML has a flag that applies across an entire score to expresses that the score is a chord-only chart.  And then it would be the responsibility of whatever program that reads the MusicXML program to recognize that flag, and if detected then apply a special treatment when importing and load a special or user-defined style.

In the meantime, I think I might personally make a couple edits to my own self-compiled musescore to do this exact type of treatment, and then just delete that treatment.

**Comment by infojunkie** [comment]
> The ideal solution I imagine would be that MusicXML has a flag that applies across an entire score to expresses that the score is a chord-only chart. 

As far as I understand, this only exists at the measure level as [`measure-style/slash`](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-slash.htm) and that's what I propose to [fix in MuseScore](https://musescore.org/en/node/313946).

Regarding the other customizations, I expect most of them to be available in MusicXML via the [`print` element](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-print.htm), but I need to make a deeper dive before being sure.

**Comment by ericfont** [comment]
Aha.  Yeah, your specific MuseScore feature request (MusicXML import should honor "measure-style/slash") sounds like a feature that needs to be implemented.

If there was a flag that applies to a particular instrument/part/staff, then whatever imports the MusicXML would know that individual staff lines aren't necessary for that particular chord-symbol-only instrument/part/staff, and so could know to disable staff lines or make staff lines invisible for that part/staff.  Unfortunately considering how hard it is to change standards, I wouldn't bother trying to add a new flag.

I think there has been a recurring feature request in musescore forms over the years to be able to render chord-symbols only, without even having a staff or slash notes/beats, so can look just like iReal does with the chord symbols between bar lines.

**Comment by infojunkie** [comment]
The problem with how iReal renders the chords is that it's really hard to tell their onset and duration. I personally prefer slash rhythmic notation.

**Comment by ericfont** [comment]
oh yeah, I agree too.  Though I am sure there many people simply accustomed to iReal's display method, and it does have the advantage on small cellphone screens of proving the most important content in the most readable fashion (though at the cost of losing info about onset and duration).

Regardless of the best way to display, I suppose those debates are out of scope of this github project.  And if someone is so inclined to replicate iReal display, they could created their own app that applies whatever rendering method to the MusicXML chord charts.

**Comment by infojunkie** [comment]
Here's a decent rendering of a full lead sheet. Now that I'm working on [`musicxml-mscx` ](https://github.com/infojunkie/musicxml-mscx) to explicitly convert MusicXML scores to MuseScores, maybe we can use some of the styling information here in that conversion tool.

![9 20-special-1](https://github.com/user-attachments/assets/59cc2825-2cae-4c9b-b0b5-c4bbed8d0e38)

**Comment by infojunkie** [comment]
Also found this beautiful style at https://musescore.com/user/36194540/scores/20509711

![Whats_Love_Got_To_Do_With_It_Lead_Sheet_-_Tina_Turner-1](https://github.com/user-attachments/assets/970557dd-7007-43f3-bb68-6d0032ced30e)

**Comment by infojunkie** [comment]
Closing this issue now that [`musicxml-mscx`](https://github.com/infojunkie/musicxml-mscx) has launched. @ericfont , if you're still interested, please join me there to add your own styles or enhance existing ones.
