### ISSUE TITLE
cli fixes

### ISSUE THREAD

**Issue by infojunkie** [infojunkie/ireal-musicxml#17]
- Don't crash
- Report conversion errors

**Comment by ericfont** [comment]
The moment when start processing a new song, would be nice for the cli to print something like "Processing song $n / $total: $songname"

**Comment by infojunkie** [comment]
k that was easy :smile: plz try it now

**Comment by ericfont** [comment]
nice.  It is also able to complete all 1350 on my computer too.  Maybe simply by virtue of breaking the output up on a song-by-song, that might have had the byproduct of removing the crash.

**Comment by ericfont** [comment]
I see from your commit, that the try/catch blocks are done on an individual song basis.  So that is why the whole thing doesn't crash...good.

**Comment by ericfont** [comment]
Here are the problem scores:

ireal2musicxml: Error converting "All Or Nothing At All" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Brazilian Suite" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Bud Powell" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Cabin in the Sky" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Corcovado" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Crepuscule With Nellie" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Driftin'" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Ill Wind" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "In a Sentimental Mood" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Invitation" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "It's Only a Paper Moon" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Lover Man" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Memories Of You" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "My One And Only Love" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "On The Sunny Side Of The Street" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Polkadots And Moonbeams" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Prelude To A Kiss" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Speak Low" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Spring Can Really Hang You Up The Most" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "That's All" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "There's A Small Hotel" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Travels" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "Yesterday's Gardenias" TypeError: Cannot read property 'spaces' of undefined
ireal2musicxml: Error converting "You Took Advantage Of Me" TypeError: Cannot read property 'spaces' of undefined

**Comment by ericfont** [comment]
I believe those above are the only errors which result in *crashes*.

The majority of the remaining console output consist of either of the following likely benign/recoverable errors:
1. [MusicXML.adjustChordDuration] Too many beats (4 out of 3) in measure 1. Removing some spaces...
2. [MusicXML.convertChord] Unhandled alternate chord {"note":"C","modifiers":"^7","over":null,"alternate":null}
3. [MusicXML.convertMeasures] Unhandled empty/alternate chord {"note":" ","modifiers":"","over":null,"alternate":{"note":"Ab","modifiers":"-7","over":null,"alternate":null}}
4. [MusicXML.convertMeasures] Starting a new measure over existing measure ...
5. [MusicXML.convertMeasures] Found non-empty orphan cell {"annots":[],"comments":[],"bars":")","spacer":0,"chord":null}.

(and there are some variants of that alternate chord error)

**Comment by infojunkie** [comment]
Thanks a lot for taking the time to go through the log - that's a great help. Yes, the messages starting with `[MusicXML.XXX]` are expected cases that indicate situations that may or may not need fixing, but that are not crashing the converter. I'll fix the `TypeError: Cannot read property 'spaces' of undefined` error first.

**Comment by infojunkie** [comment]
Fyi, `Unhandled alternate chord` means that iReal Pro specifies an alternate chord in small font (but does not play it), and I ignore this info. If you think it's important to show on your charts, please +1 #2

**Comment by ericfont** [comment]
Case 4 "[MusicXML.convertMeasures] Starting a new measure over existing measure" seems to be a genuine error which needs to be fixed.  I've separated to a separate issue #20.
