### ISSUE TITLE
cli output "[MusicXML.convertMeasures] Starting a new measure over existing measure" seems to result in scores that are missing measures

### ISSUE THREAD

**Issue by ericfont** [infojunkie/ireal-musicxml#20]
So far (as I've been uploading scores that start with the letter 'A') I've encountered two resulting MusicXML that have missing measures ("A Ballad" and "After You").  I don't have the iReal app, so I initially assumed that was an error in the iReal score, not the translation.  But looking at the cli output, I'm noticing a certain pattern...these two scores produce this characteristic message:

```
[MusicXML.convertMeasures] Starting a new measure over existing measure
```

The translation for "A Ballad" ([A Ballad.zip](https://github.com/infojunkie/ireal-musicxml/files/5640191/A.Ballad.zip)) is missing a measure between measures 24 and 25:

![image](https://user-images.githubusercontent.com/6502474/101113706-f458b280-35ad-11eb-9d16-e71014746cf9.png)

That missing measure I've had to manually insert, selected in blue here:

![image](https://user-images.githubusercontent.com/6502474/101113868-4c8fb480-35ae-11eb-899f-deb51478299c.png)

And I'm notice "After You" ([After You.zip](https://github.com/infojunkie/ireal-musicxml/files/5640204/After.You.zip)) also similarly is missing measures just prior to the [B] section:

![image](https://user-images.githubusercontent.com/6502474/101113954-7943cc00-35ae-11eb-9b19-1baf5c879e6d.png)

So based on what I've seen so far, my first hunch is that somehow the new section is resulting in the measures just prior to the start of the new section being overwritten.

**Comment by ericfont** [comment]
So with "After You", it seems the error is that just before where section [B] is indicated, there should be a measure inserted.  And the real section [B] only start after the D7b9 chord.

I don't have the iReal app, so I don't know what exactly the iReal database says should exist there, though.  My first guess is a measure of D7 chord should be inserted before that Gmaj7.

**Comment by infojunkie** [comment]
My fix for this issue and #18 is the same - I think. I'd be very grateful if you could try now on the updated demo (or the updated cli).

**Comment by ericfont** [comment]
Ah nice.  Yes I've verified that commit has fixed this issue of missing measures on both these two scores.

(Seems I even predicted the correct missing measure, lol.)

I am a little suspicious of this "After You" because that [B] section is still in the incorrect spot.  The [B] should start after that D7b9 chord, so that there is an even 16 measures in the [A] section.

Also the real name of the song is "After You, Who?", and I'm wondering if maybe the command and question mark in the title have somehow caused the translation to drop the ", Who?" from the title.

I don't have the original iReal Pro app to verify this, though...but if you do maybe check that out.

**Comment by infojunkie** [comment]
Thanks, I'll be checking the additional cases in your last comment.

**Comment by infojunkie** [comment]
>  I am a little suspicious of this "After You" because that [B] section is still in the incorrect spot. 

I checked against iReal Pro - seems correct.

> Also the real name of the song is "After You, Who?", [...]

The iReal Pro chart calls it "After You". 

![![Screenshot_20201204-103834](https://user-images.githubusercontent.com/92977/101202663-6963d080-361e-11eb-9559-8bf3f4f6f037.png)
](https://user-images.githubusercontent.com/92977/101202663-6963d080-361e-11eb-9559-8bf3f4f6f037.png)... I'd be grateful if you double-checked!

If all checks out on your side, this issue can be closed :pray:

**Comment by ericfont** [comment]
ok.  So this is not a bug in the translation, but rather the iReal database is at fault for the incomplete title and misplaced [B] section.
