### ISSUE TITLE
Parsing error on a big file

### ISSUE THREAD

**Issue by wardner9** [infojunkie/ireal-musicxml#55]
Hi, just tried to parse this huge URI (726 sheets) found here:

http://replist.brstudioz.com/replist.html

but no output is shown in the webdemo. Could it be that the URI is too long to handle?

**Comment by infojunkie** [comment]
Thanks! I confirm that this file crashes the module - looking into it.

**Comment by infojunkie** [comment]
It's now fixed on the demo. The app was choking on some songs that are empty, like "Cry Me A River", "Family Affair" and "I Took A Pill In Ibiza". 

Note that some songs are still problematic (e.g. "(Everything I Do) I Do It For You") but at least the playlist is imported. 

Thanks for your report and sharing those songs!

**Comment by wardner9** [comment]
Thank you!
