### ISSUE TITLE
Causes Exception on Band in a Box when importing this .musicxml

### ISSUE THREAD

**Issue by User2X** [infojunkie/ireal-musicxml#56]
html file contains 12 songs. Song 8 gives an exception:
"Could not convert variant of type (Null) into type (OleStr)."
I have added a .zip file containing the source html file and the converted .musucxml file of track no 8, which gives this problem.

All other exported files from this html work fine.

[Set2.zip](https://github.com/infojunkie/ireal-musicxml/files/10149693/Set2.zip)

**Comment by infojunkie** [comment]
Thanks I'll take a look soon.

**Comment by infojunkie** [comment]
I performed a couple of tests on the attached MusicXML file:
- Validating it against the MusicXML schema as per https://blog.karimratib.me/2020/11/17/validate-musicxml.html 
- Loading it with MuseScore 3.6.2

Both these tests passed without problem. I also examined the file manually but could not identify a significant difference from the others in the "NODO Set 2" playlist which I also generated.

So I resaved the MusicXML file from MuseScore, attached here. Please try it and report here if it still crashes Band-in-a-Box. 

[Far-Away-Blues-CG-2-resaved.zip](https://github.com/infojunkie/ireal-musicxml/files/10173463/Far-Away-Blues-CG-2-resaved.zip)

**Comment by User2X** [comment]
Hello,

Thank you!
The Musiscore resaved export you sent works in BIAB. So there has to be some obscure difference somewhere.

Best regards
Bernt
     On Wednesday, 7 December 2022, 07:16:41 pm AEDT, Karim Ratib ***@***.***> wrote:  
 
 


I performed a couple of tests on the attached MusicXML file:
   
   - Validating it against the MusicXML schema as per https://blog.karimratib.me/2020/11/17/validate-musicxml.html
   - Loading it with MuseScore 3.6.2

Both these tests passed without problem. I also examined the file manually but could not identify a significant difference from the others in the "NODO Set 2" playlist which I also generated.

So I resaved the MusicXML file from MuseScore, attached here. Please try it and report here if it still crashes Band-in-a-Box.

Far-Away-Blues-CG-2-resaved.zip

**Comment by infojunkie** [comment]
Thanks. I'll close this and only look deeper into it if more issues occur with BIAB.
